plugin: aws_ec2

regions:
  - ap-south-1
 
filters:
  instance-state-name : running

keyed_groups:
  - key: tags.Name
    prefix: ""
    seperator: ""
hostnames:
  - private-ip-address
compose: 
  ansible_host: private_ip_address
